spring:
  datasource:
    #db
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
    ####################################
    # Druid Config                     #
    ####################################
    druid:
      # 初始化连接大小[0]
      initial-size: 10
      # 最小空闲连接数[0]
      min-idle: 10
      # 最大连接数[8]
      max-active: 100
      # 配置获取连接等待超时的时间(毫秒)[-1]
      max-wait: 60000
      # 查询超时时间(秒)
      query-timeout: 90
      # 申请连接时检测连接可用性[false]
      test-on-borrow: false
      # 归还连接检测[false]
      test-on-return: false
      # 超时是否检测连接可用性[true]
      test-while-idle: true
      # 每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接 (毫秒)
      time-between-eviction-runs-millis: 60000
      #  配置一个连接在池中最小生存的时间(毫秒，默认30分钟)
      min-evictable-idle-time-millis: 300000
      # 用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 'x'
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 是否缓存PreparedStatement. PSCache对支持游标的数据库性能提升巨大，比如说oracle.在mysql下建议关闭.
      pool-prepared-statements: false
      # 通过别名的方式配置扩展插件，常用的插件有：监控统计用的filter:stat；日志用的filter:log4j；防御sql注入的filter:wall
      filters: stat,wall,slf4j
      # StatFilter [https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatFilter]
      filter:
        stat:
          # SQL合并
          merge-sql: false
          db-type: mysql
          #慢SQL记录
          slow-sql-millis: 2000
          log-slow-sql: true
        # WallFilter [https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE-wallfilter]
        wall:
          db-type: mysql
          config:
            drop-table-allow: false
            delete-allow: false
          enabled: true
      # StatViewServlet [https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatViewServlet%E9%85%8D%E7%BD%AE]
      # 监控页面的用户名和密码
      stat-view-servlet:
        url-pattern: /druid/*
        login-password: admin
        reset-enable: false
        login-username: admin
        enabled: true
